language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "nightly"
# command to install dependencies
install: "pip install -q -U PyYAML requests coveralls"
# command to run tests
script: "coverage run --source=configmaster setup.py test"
after_success: "coveralls"